# AWS 테스트를 위한 localstack 테스트환경 구축 컨테이너
version: "3.8"

services:

  localstack:
    image: "localstack/localstack:3"
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3, sqs, lambda
      - DEBUG=1
      - DEFAULT_REGION=ap-northeast-2
    volumes:
      - "./localstack-init:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./lambda:/etc/localstack/lambda"
    networks:
      - localnet

  spring-server:
    build:
      context: .
      dockerfile: spring-server/Dockerfile
    container_name: spring-server
    ports:
      - "8080:8080"
    networks:
      - localnet
    depends_on:
      - localstack

networks:
  localnet: