# AWS 테스트를 위한 localstack 테스트환경 구축 컨테이너
version: "3.8"

services:
  localstack:
    image: "localstack/localstack"
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker/sock
    volumes:
      - "./.localstack:/tmp/localstack" # 로컬에 데이터 유지
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-aws.sh:/etc/localstack/init/read/d/init-aws.sh" # 도커 실행시 init-aws.sh를 읽어 자동 실행 !
