# TODO infra-aws 이전 예정
aws:
  profile: local
  region: ap-northeast-2
  secret:
    name: dev/aws/credentials
  s3:
    bucket: mini-drive-dev-upload
    upload-prefix: uploads

# TODO infra kafka 이전 예정
spring:
  kafka:
    bootstrap-servers:
      - kafka-broker:29092
      
thumbnail:
  domain: https://cdn.mini-drive.dev/
