# AWS 테스트를 위한 localstack 테스트환경 구축 컨테이너
services:

  localstack:
    image: "localstack/localstack:3"
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3, sqs, lambda, logs
      - REGION=ap-northeast-2
      - LAMBDA_EXECUTOR=local
      - PORT_WEB_UI=8080
      - KINESIS_ERROR_PROBABILITY=0.25
    volumes:
      #- "${INIT_DIR}:/etc/localstack/init/ready.d"
      #- "${LAMBDA_DIR}:/etc/localstack/lambda"
      - "${ROOT_DIR}/module-lambda/build/lambda-zip:/var/task/lambda-zip"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localnet

  spring-server:
    build:
      context: "${ROOT_DIR}"
      dockerfile: "${ROOT_DIR}/module-api/Dockerfile"
    container_name: spring-server
    ports:
      - "8080:8080"
    networks:
      - localnet
    depends_on:
      - localstack

networks:
  localnet: