aws:
  profile: local
  region: ap-northeast-2
  secret:
    name: dev/aws/credentials
  s3:
    bucket: mini-drive-dev-upload
    upload-prefix: uploads

spring:
  kafka:
    bootstrap-servers:
      - kafka-broker:29092